### ISSUE TITLE
Add ability to overwrite config file

### ISSUE THREAD

**Issue by Lusitaniae** [gantsign/ansible-role-atom#38]
I think it would be interesting to have the option to overwrite the config file for atom, this would be disabled by default. 

Current code:
```

- name: write config
  become: yes
  template:
    src: config.cson.j2
    dest: '~{{ item.username }}/.atom/config.cson'
    force: no
    owner: '{{ item.username }}'
    group: '{{ item.username }}'
    mode: 'u=rw,go='
  with_items: '{{ users }}'
  when: "item.atom_config is defined and item.atom_config not in ({}, '', None, omit)"
```

I can submit a PR if you like the idea.
